export const Icons = {
  details: {
    ref: 'detailsBtn',
    handler: 'openDetails',
    type: 'icon', // 'icon' | 'flat'
    name: 'info_outline',
    tooltip: 'general.icons.tooltip.open_details',
    style: 'color: #B27D49;',
  },
  edit: {
    ref: 'editBtn',
    handler: 'onEdit',
    type: 'icon',
    name: 'edit',
    tooltip: 'general.icons.tooltip.edit_item',
    style: 'color: #0084b8;',
  },
  delete: {
    ref: 'deleteBtn',
    handler: 'onDelete',
    type: 'icon',
    name: 'delete_outline',
    tooltip: 'general.icons.tooltip.delete_item',
    style: 'color: #A5300F;',
  },
  montant: {
    ref: 'montantBtn',
    handler: 'onPaye',
    type: 'icon',
    name: 'attach_money',
    tooltip: 'general.icons.tooltip.payement',
    style: 'color: #BCAF4D;',
  },
  download: {
    ref: 'downloadBtn',
    handler: 'onDownload',
    type: 'icon',
    name: 'file_download_outline',
    tooltip: 'general.icons.tooltip.download_doc',
    style: 'color: #28a745;',
  },
  replace: {
    ref: 'ReplaceBtn',
    handler: 'onReplace',
    type: 'icon',
    name: 'sync',
    tooltip: 'general.icons.tooltip.replace_item',
    style: 'color: #19c8a6;',
  },
  descriptionFile: {
    ref: 'downloadDescFileBtn',
    handler: 'onDownloadDescFile',
    type: 'icon',
    name: 'description_outline',
    tooltip: 'general.icons.tooltip.liste_plainte',
    style: 'color: #19c8a6;',
  },
  show: {
    ref: 'showBtn',
    handler: 'onshow',
    type: 'icon',
    name: 'search',
    tooltip: 'show',
    style: 'color: #0daef9;',
  },
  showfile: {
    ref: 'showfileBtn',
    handler: 'onshowfile',
    type: 'icon',
    name: 'search',
    tooltip: 'search',
    style: 'color: #0daef9;',
  },
  calendar: {
    ref: 'calendarBtn',
    handler: 'onClickCalendar',
    type: 'icon',
    name: 'date_range',
    tooltip: 'general.icons.tooltip.calendar',
    style: 'color: #0DAEF9;',
  },
  notify: {
    ref: 'notificationBtn',
    handler: 'onNotify',
    type: 'icon',
    name: 'notifications_active',
    tooltip: 'general.icons.tooltip.notify',
    style: 'color: #f4ab2c;',
  },
  validate: {
    ref: 'validateBtn',
    handler: 'onValidate',
    type: 'icon',
    name: 'check_circle',
    tooltip: 'general.icons.tooltip.validate',
    style: 'color: #19c8a6;',
  },
  cancel: {
    ref: 'cancelBtn',
    handler: 'onCancel',
    type: 'icon',
    name: 'cancel',
    tooltip: 'general.icons.tooltip.cancel',
    style: 'color: #cc0000;',
  },
  history: {
    ref: 'historyBtn',
    handler: 'onHistory',
    type: 'icon',
    name: 'history',
    tooltip: 'general.icons.tooltip.history',
    style: 'color: #af1414;',
  },
};
